### ISSUE TITLE
boa noite O PSCONTAS 

### ISSUE THREAD

**Issue by lamenta123** [Bronce/PSTeam#13]
O PScontas nao ta criando contas nao  v7.14 nao ta pegando nao 

mas tudo é muito bom muito obrigado por vc criar mods pra agente

**Comment by lamenta123** [comment]
![Screenshot_20191126-063115](https://user-images.githubusercontent.com/58211122/69676265-21ab8000-107f-11ea-8277-6124eab72d5c.png)
  
olha o erre ai muito abrigado ta

**Comment by Caua16** [comment]
Verdade o meus tmbm estar

**Comment by pretosilva1234** [comment]
> O PScontas nao ta criando contas nao v7.14 nao ta pegando

**Comment by lamenta123** [comment]
![Screenshot_20191204-203652](https://user-images.githubusercontent.com/58211122/70190841-d1af6780-16d5-11ea-91bf-14224f4d30d6.png)






nao acredito nao mano poxa nao faz isso nao  porra vei eu quero fala como vcs nao pode nao viu

**Comment by lamenta123** [comment]
como que eu fasso pra paga
